### ISSUE TITLE
Hey Ho!

### ISSUE THREAD

**Issue by mat0thew** [ac-pm/SSLUnpinning_Xposed#1]
This app doesnt work with Twitch, Skrill. 

I am used Fiddler4 + Android. 

Any ideas?

**Comment by ac-pm** [comment]
Hi mat0thew, 

At this time only JSSE and Apache libraries are hooked. It is possible that these applications are using other libraries. For example Volley or LoopJ.

Soon, other libraries will be included.

**Comment by mat0thew** [comment]
Okay, thanks

**Comment by mat0thew** [comment]
@ac-pm you will continue to work on the project? an interesting tool for testing applications

**Comment by youdy3000** [comment]
Hi @ac-pm,

Any chance you will add support for SSLUnpinning (with Xposed) for apps that use Volley?

I can use your Cydia substrate SSLUnpinning apk.  Works perfectly.  But when I use the Xposed framework & SSLUnpinning it does not work.  It does seem to perform an SSL Strip style functionality but nothing more.  I also tried to use the library on the Twitter Android app(which I guess uses Twitter's okhttp?).

Rob
