### ISSUE TITLE
can you support magisk?

### ISSUE THREAD

**Issue by 687766616e** [ac-pm/SSLUnpinning_Xposed#17]

**Comment by tmjvonboss** [comment]
give more details about your test environment

i use android 9.0 with magisk 19.3 and Edxposed 90.0-v0.4.5.5_beta(4468) SANDHOOK on my OnePlus 3 and it works perfectly

**Comment by 687766616e** [comment]
ill try it later

**Comment by tmjvonboss** [comment]
how did it go?

If it doesn't work for you, may want to switch over to Frida + objection

Though that requires you to set it up on a computer to do hooking

**Comment by 687766616e** [comment]
it works
