### ISSUE TITLE
Does not disable certificate pinning - DROID 4 (4.1.2)

### ISSUE THREAD

**Issue by xteraflopx** [ac-pm/SSLUnpinning_Xposed#2]
After installing Xposed Framework, rebooting, activating SSLUnpinning, rebooting, apply bypass to an app, reboot, there is still no captured traffic from apps that use certificate pinning.

Also does not disable certificate pinning when used from a virtual machine.

**Comment by ac-pm** [comment]
At this time only JSSE and Apache libraries are hooked. It is possible that your applications are using other libraries. For example Volley or LoopJ.

If not is this case, I can debug. Are public apps?

Just remember, even removing the pinning, the requests will be https.

**Comment by xteraflopx** [comment]
The app I am testing with is "Instagram". Instagram uses "httpclientandroidlib" which I assume is one of the Apache libraries you are speaking of.

I am using Charles Proxy as my proxy app to view HTTP/HTTPS requests, and since I have the Charles root certificate installed, I am able to view HTTPS requests without any problem.

**Comment by ac-pm** [comment]
Ok, after look inside instagram (decompiled), i saw the "ch.boye.httpclientandroidlib" library. 

Sorry, but at this time, if the package is not "javax.net..." or "org.apache.http..." the hooks not will work.

![instagram1](https://cloud.githubusercontent.com/assets/1753643/13020623/4260d7bc-d1b5-11e5-8fbf-8e479be1d89a.png)

**Comment by xteraflopx** [comment]
An interesting project that I would try if I had enough experience, would be to hook the function from /system/lib/libssl.so that generates the master_secret for an SSL session. Then you could analyse all traffic with Wireshark, and certificate pinning wouldn't even be a problem.

**Comment by ac-pm** [comment]
@xteraflopx, I was able to intercept some of instagram requests. As you can see in the following post some requests are in plain text.

https://www.reddit.com/r/netsec/comments/20j7rk/instagram_implemented_certificate_pinning_but/

Another thing, some http libraries are unaffected by android proxy, then i could only intercept after making a arpspoof and redirect the traffic to the proxy.
![instagram2](https://cloud.githubusercontent.com/assets/1753643/13024962/4d5f3b00-d1dc-11e5-84c0-7ffbf9703beb.png)

Apply a hook to libssl.so is very interesting, unfortunately the Xposed only works with java libraries.

**Comment by 01100100011010010110001101101011** [comment]
It is time to dismantle **JNI**?

**Comment by ac-pm** [comment]
I think so!

**Comment by xteraflopx** [comment]
@ac-pm How would one do that?
