### ISSUE TITLE
pinning not bypassed - same as #3

### ISSUE THREAD

**Issue by javixeneize** [ac-pm/SSLUnpinning_Xposed#6]
Hi

I have installed and tested this application and it doesnt work well at all with android 5.1.1

I have tried to bypass pinning in 3 different applications but it didnt work at all in any of them

Thanks

**Comment by ac-pm** [comment]
Hi @javixeneize 

At this time only JSSE and Apache libraries are hooked. It is possible that your applications are using other libraries. For example Volley or LoopJ.

**Comment by javixeneize** [comment]
Thats correct. Its volley what i am using

Any plan to release a version that can work with it?

**Comment by ac-pm** [comment]
I'm working on the project [Inspeckage](https://github.com/ac-pm/Inspeckage) which also has this functionality and many others. Soon this feature will be present there and here.

Thanks @javixeneize

**Comment by javixeneize** [comment]
That sounds pretty interesting!

Are you open to colaborations in this project?

**Comment by ac-pm** [comment]
Of course! Feel free to collaborate with us. I guarantee it that all your commits will be welcome.

**Comment by javixeneize** [comment]
Hi

Development is not my top skill... i meant something more focused on
testing the app or suggesting improvements on it

For example, i have tested it with an app and i have seen a strange
behaviour. Same thing with inspeckage (i love it by the way!)

Do you have a personal mail where i can reach you?

**Comment by javixeneize** [comment]
Hi

Can i ask how the crypto information is collected?

ThNks

**Comment by ac-pm** [comment]
Hi @javixeneize I will close this issue and send email for you.
